dist: trusty
language: node_js
node_js:
  - 11

addons:
  chrome: stable
  artifacts: true
  sonarcloud:
    organization: "3r1co-github"

env:
 - IMAGE_NAME=868894423383.dkr.ecr.eu-west-1.amazonaws.com/juice-shop:1.0-$TRAVIS_BUILD_NUMBER
services:
  - docker

install: true

before_script:
  - mkdir -p $HOME/bin
  - wget https://bintray.com/jeremy-long/owasp/download_file?file_path=dependency-check-5.0.0-M3-release.zip -O $HOME/bin/dc.zip
  -  cd $HOME/bin/ && unzip dc.zip

script:
  - npm install
  - $HOME/bin/dependency-check/bin/dependency-check.sh --project juice-shop -s . 
